package model.AM.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 18 20:53:54 IST 2018
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void callCommit();
}
