package model.AM;


import model.AM.common.AppModule;

import oracle.jbo.Transaction;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 18 20:52:23 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    /**
     * Container's getter for XxfndScheduleListT_VO1.
     * @return XxfndScheduleListT_VO1
     */
    public ViewObjectImpl getXxfndScheduleListT_VO1() {
        return (ViewObjectImpl)findViewObject("XxfndScheduleListT_VO1");
    }

    /**
     * Container's getter for XxfndScheduleT_VO1.
     * @return XxfndScheduleT_VO1
     */
    public ViewObjectImpl getXxfndScheduleT_VO1() {
        return (ViewObjectImpl)findViewObject("XxfndScheduleT_VO1");
    }

    /**
     * Container's getter for XxfndScheduleT_VO2.
     * @return XxfndScheduleT_VO2
     */
    public ViewObjectImpl getXxfndScheduleT_VO2() {
        return (ViewObjectImpl)findViewObject("XxfndScheduleT_VO2");
    }


    /**
     * Container's getter for Schedule_STVO1.
     * @return Schedule_STVO1
     */
    public ViewObjectImpl getSchedule_STVO1() {
        return (ViewObjectImpl)findViewObject("Schedule_STVO1");
    }

    /**
     * Container's getter for LookupROVO1.
     * @return LookupROVO1
     */
    public ViewObjectImpl getLookupROVO1() {
        return (ViewObjectImpl)findViewObject("LookupROVO1");
    }

    /**
     * Container's getter for XxpmSetupDetailVO1.
     * @return XxpmSetupDetailVO1
     */
    public ViewObjectImpl getXxpmSetupDetailVO1() {
        return (ViewObjectImpl)findViewObject("XxpmSetupDetailVO1");
    }


    public void callCommit() {
        this.getTransaction().commit();
    }


    /**
     * Container's getter for XxfndScheduleListT_VO2.
     * @return XxfndScheduleListT_VO2
     */
    public ViewObjectImpl getXxfndScheduleListT_VO2() {
        return (ViewObjectImpl)findViewObject("XxfndScheduleListT_VO2");
    }

    /**
     * Container's getter for Schedule_VL1.
     * @return Schedule_VL1
     */
    public ViewLinkImpl getSchedule_VL1() {
        return (ViewLinkImpl)findViewLink("Schedule_VL1");
    }
}
